In [1]:

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [7]:
df = pd.read_csv("../Resources/cleaned_telecom_data.csv")
# Drop the null columns where all values are null
df = df.dropna(axis='columns', how='all')
# Drop the null rows
df = df.dropna()
df.head()

,customerid,gender,seniorcitizen,partner,dependents,tenure,phoneservice,multiplelines,internetservice,onlinesecurity,...,deviceprotection,techsupport,streamingtv,streamingmovies,contract,paperlessbilling,paymentmethod,monthlycharges,totalcharges,churn
0,7010-BRBUU,Male,0,Yes,Yes,72,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.10,1734.65,No
1,9688-YGXVR,Female,0,No,No,44,Yes,No,Fiber optic,No,...,Yes,No,Yes,No,Month-to-month,Yes,Credit card (automatic),88.15,3973.2,No
2,9286-DOJGF,Female,1,Yes,No,38,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),74.95,2869.85,Yes
3,6994-KERXL,Male,0,No,No,4,Yes,No,DSL,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,55.90,238.5,No
4,2181-UAESM,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,No,No,No,Month-to-month,No,Electronic check,53.45,119.5,No

In [13]:
# dependent and independent values
data = df.drop(['churn','customerid'], axis = 1)
data = pd.get_dummies(data)
target = df['churn'].values.reshape(-1,1)
target_names = ["No", "Yes"]
print(data.shape,target.shape)
data.head()

(5986, 5655) (5986, 1)

,seniorcitizen,tenure,monthlycharges,gender_Female,gender_Male,partner_No,partner_Yes,dependents_No,dependents_Yes,phoneservice_No,...,totalcharges_992.7,totalcharges_994.55,totalcharges_994.8,totalcharges_995.35,totalcharges_996.85,totalcharges_996.95,totalcharges_998.1,totalcharges_999.45,totalcharges_999.8,totalcharges_999.9
0,0,72,24.10,0,1,0,1,0,1,0,...,0,0,0,0,0,0,0,0,0,0
1,0,44,88.15,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,38,74.95,1,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,4,55.90,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,2,53.45,0,1,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

In [15]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(X_train, y_train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)

ValueError: could not convert string to float: 'No'